# Generated by Django 3.0.7 on 2020-08-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mobile_no', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('status', models.BooleanField(default='null')),
            ],
        ),
    ]
